"""
Project: Waste Management VRP Optimization - Universitas Gunadarma
File: VRP_Solver_revised.py
Author: Maulida Boru Butar Butar

Description:
    Solves the directed Capacitated Vehicle Routing Problem (CVRP)
    for institutional waste collection using Google OR-Tools.

    Supported scenarios:
    - Normal
    - Buffered
    - Peak

    In the Peak scenario, two OR-Tools route indices are interpreted
    as two sequential virtual trips performed by one physical vehicle.
"""

from __future__ import annotations

import argparse
import json
import platform
import time
from pathlib import Path
from statistics import mean
from typing import Any

import ortools
from ortools.constraint_solver import pywrapcp, routing_enums_pb2


NODE_NAMES = [
    "D", "E", "G", "F4", "F5", "F6", "F7",
    "S", "C", "J1", "J3", "J6", "K"
]

DEPOT_INDEX = 0
VEHICLE_CAPACITY = 180

# Directed road-distance matrix in kilometres.
# The values retain the precision generated by the OSMnx workflow.
DISTANCE_MATRIX_KM = [
    [0.0, 3.01142576717949, 2.95682091810056, 6.61944067081717, 3.51122577683372, 5.28142647748746, 9.69041872505375, 10.9595214092752, 21.7584039968715, 26.3358140069063, 31.588078589374, 31.7447506303651, 39.6549452709769],
    [3.48426190084266, 0.0, 0.125226735784065, 3.95913460574585, 2.97745380719347, 2.62112041241615, 7.03011265998243, 10.718390897211, 20.8382502575141, 23.57240631617, 28.8246708986378, 28.9813429396288, 39.1211733013367],
    [3.42965705176373, 0.125226735784065, 0.0, 3.90452975666692, 2.92284895811454, 2.56651556333722, 6.9755078109035, 10.6637860481321, 20.8097016077685, 23.5438576664244, 28.7961222488922, 28.9527942898832, 39.0665684522577],
    [6.33343916896567, 4.08289825963574, 4.02829341055681, 0.0, 6.6908242038307, 4.43185206498145, 5.66807737473284, 14.303474594556, 22.4095977928883, 23.085011173688, 28.2166676631179, 28.6666059978193, 39.3231131010964],
    [2.07539130959217, 3.50459756086112, 3.44999271178219, 5.76203954316628, 0.0, 5.77459827116909, 10.1835905187353, 11.4526932029568, 22.2515757905531, 26.8289858005879, 32.0812503830557, 32.2379224240467, 36.6696413902217],
    [5.74498421438904, 2.6302501765449, 2.57564532746597, 4.57756280774551, 5.23817612073986, 0.0, 5.04218401741873, 11.3136179548579, 19.4197411531903, 21.6635033327189, 26.7042619768055, 26.8609340177966, 41.245177511975],
    [10.1500353296894, 7.03530129184526, 6.98069644276633, 5.2932348723939, 9.64322723604022, 5.17536496201773, 0.0, 12.0962622770882, 19.9878679781546, 17.8010979380088, 22.8418565820954, 22.9985286230865, 42.0278218342053],
    [10.8870067947814, 9.93736933224832, 9.88276448316939, 12.8708002141622, 10.3801987011322, 10.0529752244106, 11.0896333909999, 0.0, 14.5951243929811, 20.9929459711726, 26.2472232335345, 26.4038952745255, 34.5352258980666],
    [21.1225201820965, 20.1728827195634, 20.1182778704845, 21.9870211376767, 20.6157120884473, 19.2542417530275, 19.0964111053808, 13.7649576310764, 0.0, 16.6982093545016, 22.4044259637695, 24.2248085374256, 31.5404014712302],
    [26.1918895337794, 22.9649249846671, 22.9363763349215, 22.5356781931306, 25.6850814401302, 21.4926873337501, 17.631380002151, 21.0270197196232, 17.5864814587315, 0.0, 7.93523054534609, 8.09190258633712, 45.3589055651183],
    [31.7670849122967, 28.5401203631844, 28.5115717134388, 27.9219626819251, 31.2602768186475, 26.4900351411302, 22.6287278095312, 27.392061000974, 23.9515227400823, 6.87444065671253, 0.0, 8.03364412952705, 51.7239468464691],
    [28.0815888815144, 24.854624332402, 24.8260756826564, 24.4253775408656, 27.5747807878652, 23.382386681485, 19.5210793498859, 22.9167190673581, 18.2084828306331, 4.29780254210867, 10.7244121826686, 0.0, 47.2502292154309],
    [37.3735359323145, 39.1446098246271, 39.0900049755482, 40.0264749158154, 39.587439193511, 41.414610534935, 43.149729941195, 32.3973666721914, 30.9250278657029, 46.1116724547302, 52.5382820952902, 53.8487041284591, 0.0],
]

SCENARIOS = {
    "normal": {
        "demands": [0, 10, 8, 14, 12, 9, 11, 13, 16, 10, 8, 9, 6],
        "num_trips": 1,
    },
    "buffered": {
        "demands": [0, 12, 10, 17, 14, 11, 13, 16, 19, 12, 10, 11, 7],
        "num_trips": 1,
    },
    "peak": {
        "demands": [0, 15, 12, 20, 18, 14, 16, 20, 24, 15, 13, 14, 10],
        "num_trips": 2,
    },
}

# Documented manual route:
# D -> E -> G -> F6 -> F5 -> F4 -> F7 -> S ->
# J6 -> J1 -> J3 -> C -> K -> D
MANUAL_ROUTE = [0, 1, 2, 5, 4, 3, 6, 7, 11, 9, 10, 8, 12, 0]


def validate_inputs() -> None:
    """Validate matrix and scenario dimensions before solving."""
    size = len(NODE_NAMES)

    if len(DISTANCE_MATRIX_KM) != size:
        raise ValueError("Distance matrix row count does not match node count.")

    if any(len(row) != size for row in DISTANCE_MATRIX_KM):
        raise ValueError("Distance matrix must be square.")

    for scenario_name, scenario_data in SCENARIOS.items():
        if len(scenario_data["demands"]) != size:
            raise ValueError(
                f"Demand length for scenario '{scenario_name}' "
                "does not match node count."
            )


def calculate_route_distance_km(route: list[int]) -> float:
    """Calculate route distance using the directed matrix."""
    if len(route) < 2:
        return 0.0

    return sum(
        DISTANCE_MATRIX_KM[route[index]][route[index + 1]]
        for index in range(len(route) - 1)
    )


def create_data_model(scenario: str) -> dict[str, Any]:
    """Create the OR-Tools input model for one scenario."""
    scenario_key = scenario.lower().strip()

    if scenario_key not in SCENARIOS:
        valid = ", ".join(SCENARIOS)
        raise ValueError(f"Unknown scenario '{scenario}'. Valid options: {valid}.")

    scenario_data = SCENARIOS[scenario_key]
    demands = list(scenario_data["demands"])
    num_trips = int(scenario_data["num_trips"])
    total_demand = sum(demands)

    if total_demand > num_trips * VEHICLE_CAPACITY:
        raise ValueError(
            f"Scenario '{scenario_key}' is infeasible: total demand "
            f"{total_demand} exceeds total trip capacity "
            f"{num_trips * VEHICLE_CAPACITY}."
        )

    return {
        "scenario_name": scenario_key,
        "distance_matrix": DISTANCE_MATRIX_KM,
        "demands": demands,
        "num_trips": num_trips,
        "trip_capacities": [VEHICLE_CAPACITY] * num_trips,
        "depot": DEPOT_INDEX,
    }


def extract_solution(
    data: dict[str, Any],
    manager: pywrapcp.RoutingIndexManager,
    routing: pywrapcp.RoutingModel,
    solution: pywrapcp.Assignment,
    runtime_seconds: float,
) -> dict[str, Any]:
    """Convert the OR-Tools solution into a structured result."""
    trips: list[dict[str, Any]] = []
    total_distance_m = 0

    for trip_id in range(data["num_trips"]):
        index = routing.Start(trip_id)
        route_indices: list[int] = []
        route_load = 0
        route_distance_m = 0

        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            route_indices.append(node_index)
            route_load += data["demands"][node_index]

            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance_m += routing.GetArcCostForVehicle(
                previous_index,
                index,
                trip_id,
            )

        route_indices.append(manager.IndexToNode(index))
        total_distance_m += route_distance_m

        # Exclude unused depot-to-depot route indices.
        if len(route_indices) <= 2:
            continue

        trip = {
            "trip_id": trip_id + 1,
            "route_indices": route_indices,
            "route_names": [NODE_NAMES[node] for node in route_indices],
            "route_text": " -> ".join(
                NODE_NAMES[node] for node in route_indices
            ),
            "distance_km": route_distance_m / 1000,
            "load_boxes": route_load,
            "capacity_boxes": VEHICLE_CAPACITY,
            "utilization_percent": (
                route_load / VEHICLE_CAPACITY
            ) * 100,
        }
        trips.append(trip)

    manual_distance_km = calculate_route_distance_km(MANUAL_ROUTE)
    total_demand = sum(data["demands"])
    manual_single_trip_feasible = total_demand <= VEHICLE_CAPACITY

    improvement_percent = None
    if manual_single_trip_feasible:
        improvement_percent = (
            (manual_distance_km - total_distance_m / 1000)
            / manual_distance_km
        ) * 100

    return {
        "scenario": data["scenario_name"],
        "status": "FEASIBLE",
        "total_demand_boxes": total_demand,
        "capacity_per_trip_boxes": VEHICLE_CAPACITY,
        "configured_trip_indices": data["num_trips"],
        "used_trips": len(trips),
        "total_distance_km": total_distance_m / 1000,
        "trips": trips,
        "manual_route_indices": MANUAL_ROUTE,
        "manual_route_text": " -> ".join(
            NODE_NAMES[node] for node in MANUAL_ROUTE
        ),
        "manual_route_distance_km": manual_distance_km,
        "manual_single_trip_feasible": manual_single_trip_feasible,
        "improvement_percent": improvement_percent,
        "runtime_seconds": runtime_seconds,
        "software": {
            "python_version": platform.python_version(),
            "ortools_version": ortools.__version__,
            "first_solution_strategy": "PATH_CHEAPEST_ARC",
            "local_search_metaheuristic": "GUIDED_LOCAL_SEARCH",
        },
    }


def solve_cvrp(
    scenario: str,
    time_limit_seconds: int = 10,
) -> dict[str, Any]:
    """Solve one CVRP scenario and return a structured result."""
    if time_limit_seconds <= 0:
        raise ValueError("time_limit_seconds must be greater than zero.")

    data = create_data_model(scenario)

    manager = pywrapcp.RoutingIndexManager(
        len(data["distance_matrix"]),
        data["num_trips"],
        data["depot"],
    )
    routing = pywrapcp.RoutingModel(manager)

    def distance_callback(from_index: int, to_index: int) -> int:
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)

        # Convert kilometres to metres and round, rather than truncate.
        return round(
            data["distance_matrix"][from_node][to_node] * 1000
        )

    transit_callback_index = routing.RegisterTransitCallback(
        distance_callback
    )
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    def demand_callback(from_index: int) -> int:
        from_node = manager.IndexToNode(from_index)
        return data["demands"][from_node]

    demand_callback_index = routing.RegisterUnaryTransitCallback(
        demand_callback
    )
    routing.AddDimensionWithVehicleCapacity(
        demand_callback_index,
        0,
        data["trip_capacities"],
        True,
        "Capacity",
    )

    search_parameters = pywrapcp.DefaultRoutingSearchParameters()
    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    )
    search_parameters.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    )
    search_parameters.time_limit.FromSeconds(time_limit_seconds)

    started_at = time.perf_counter()
    solution = routing.SolveWithParameters(search_parameters)
    runtime_seconds = time.perf_counter() - started_at

    if solution is None:
        return {
            "scenario": data["scenario_name"],
            "status": "NO_SOLUTION",
            "runtime_seconds": runtime_seconds,
        }

    return extract_solution(
        data=data,
        manager=manager,
        routing=routing,
        solution=solution,
        runtime_seconds=runtime_seconds,
    )


def print_result(result: dict[str, Any]) -> None:
    """Print one structured CVRP result in a readable format."""
    print("=" * 72)
    print(f"Scenario: {result['scenario'].upper()}")
    print(f"Status: {result['status']}")

    if result["status"] != "FEASIBLE":
        print(f"Runtime: {result['runtime_seconds']:.4f} seconds")
        return

    print(f"Total demand: {result['total_demand_boxes']} boxes")
    print(f"Trips used: {result['used_trips']}")
    print(f"Total optimized distance: {result['total_distance_km']:.3f} km")
    print(f"Runtime: {result['runtime_seconds']:.4f} seconds")

    for trip in result["trips"]:
        print("-" * 72)
        print(f"Trip {trip['trip_id']}: {trip['route_text']}")
        print(f"Distance: {trip['distance_km']:.3f} km")
        print(
            f"Load: {trip['load_boxes']}/{trip['capacity_boxes']} boxes "
            f"({trip['utilization_percent']:.1f}%)"
        )

    print("-" * 72)
    print(f"Manual route: {result['manual_route_text']}")
    print(
        f"Manual route distance: "
        f"{result['manual_route_distance_km']:.3f} km"
    )

    if result["manual_single_trip_feasible"]:
        print(
            f"Distance reduction against the documented manual route: "
            f"{result['improvement_percent']:.3f}%"
        )
    else:
        print(
            "The documented manual single-trip route is capacity-infeasible "
            "for this scenario. No Peak improvement percentage is reported "
            "until a capacity-adjusted manual comparator is defined."
        )


def save_results(results: list[dict[str, Any]], output_path: Path) -> None:
    """Save scenario results as JSON."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(results, indent=2),
        encoding="utf-8",
    )


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Solve Gunadarma institutional waste-collection CVRP."
    )
    parser.add_argument(
        "--scenario",
        choices=["normal", "buffered", "peak", "all"],
        default="all",
        help="Scenario to solve. Default: all.",
    )
    parser.add_argument(
        "--time-limit",
        type=int,
        default=10,
        help="GLS time limit in seconds. Default: 10.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/vrp_solver_results.json"),
        help="JSON output path.",
    )
    return parser.parse_args()


def main() -> None:
    """Command-line entry point."""
    validate_inputs()
    args = parse_arguments()

    scenarios = (
        ["normal", "buffered", "peak"]
        if args.scenario == "all"
        else [args.scenario]
    )

    results = []
    for scenario in scenarios:
        result = solve_cvrp(
            scenario=scenario,
            time_limit_seconds=args.time_limit,
        )
        print_result(result)
        results.append(result)

    save_results(results, args.output)
    print("=" * 72)
    print(f"Results saved to: {args.output.resolve()}")


if __name__ == "__main__":
    main()
